---
title: "qntmap"
runtime: shiny
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(shiny)
library(qntmap)
```

```{r data, include = FALSE}
td <- tempdir()
file.copy(
  system.file(package = "qntmap", "extdata", "minimal"),
  td,
  recursive = TRUE
)
xmap <- qntmap::read_xmap(file.path(td, "minimal", ".map", "1"))
.margin <- c(-.5, .5)
```


```{r select-element}
splitLayout(
  selectInput(
    "elem", label = "Element", choices = names(xmap),
    selectize = FALSE
  ),
  numericInput("min", "Min", value = NA_real_),
  numericInput("max", "Max", value = NA_real_),
  selectInput(
    "color", label = "Color", choices = c("viridis", "gray"),
    selectize = FALSE
  )
)
```


```{r}
zlim <- reactive({
  zrange <- range(xmap[[input$elem]])
  c(
    `if`(is.na(input$min) || input$min < zrange[1], zrange[1], input$min),
    `if`(is.na(input$max) || input$max > zrange[2], zrange[2], input$max)
  )
})
```


```{r output}
output$heatmap <- renderPlot(
  plot(xmap, input$elem, interactive = FALSE, colors = input$color, zlim = zlim())
)
output$histogram <- renderPlot(
  qntmap:::gghist.numeric(
    unlist(xmap[[input$elem]], use.names = FALSE),
    colors = input$color
  )
)
```


```{r}
tabsetPanel(type = "tabs",
  tabPanel(
    "Map", 
    plotOutput(
      "heatmap",
      dblclick = dblclickOpts(id = "plot_dbl_click")
    )
  ),
  tabPanel("Histogram", plotOutput("histogram"))
)
```


## Dboule click

```{r}
renderPrint({
  cat("ダブルクリックした箇所の情報:\n")
  str(input$plot_dbl_click)
})
```

```{r}
qntmap:::gghist.numeric(
  unlist(xmap[["Si"]], use.names = FALSE),
  colors = "viridis"
)
```

