codecov:
  token: fe42935e-1421-45c0-a279-4dbde95bfb2c

comment: false

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        target: auto
        threshold: 1%
