#' Generate initial centroids for clustering
#'
#' @param qnt an object generated by qnt_load or a path to the .RDS file created by qnt_load
#' @param qltmap an object generated by qltmap_load or a path to the .RDS file created by qltmap_load
#' @param wd working directory which contains .qnt directory. Use current directory if NULL
#' @param dir_map path to the directory which contains mapping data.
#' @param cnd_qltmap path to the condition file of mapping data
#' @param saving file name to save. FALSE if not saving.
#'
#' @importFrom data.table fwrite
#' @importFrom dplyr filter
#' @importFrom dplyr group_by
#' @importFrom dplyr summarise
#' @importFrom dplyr mutate
#' @importFrom pipeR %>>%
#' @importFrom tidyr spread
#'
#' @export
qltmap_cls_centers <- function(
  wd = NULL,
  dir_map,
  phase_list = NULL,
  phase_fine = NULL,
  qnt = qnt_load(wd, phase_list = phase_list),
  qltmap = qltmap_load(dir_map),
  saving = 'centers_initial0.csv'
) {

  epma_tidy( # Compile spot/map analysis
    wd,
    dir_map,
    phase_list,
    qnt = qnt,
    qltmap = qltmap,
    cluster = NA
  ) %>>%
    mutate( # Let weighting for least squares to be 0 for phases those who listed in phase_fine
      w = if(is.null(phase_fine)) {
        1
      } else {
        as.integer(!(phase %in% phase_fine))
      }
    ) %>>%
    group_by(elint) %>>% # Peform least squares and estimate 99% CI and PI
    mutate(map_est = predict(lm(map ~ 0 + pkint, weights = w))) %>>%
    mutate(
      # map_ci_L99 = qgamma(0.005, map_est + 1, 1),
      # map_ci_H99 = qgamma(0.995, map_est + 1, 1),
      map_pi_L99 = qnbinom(0.005, map_est + 1, 0.5),
      map_pi_H99 = qnbinom(0.995, map_est + 1, 0.5)
    ) %>>%
    mutate( # See if values are within CI or PI
      # within_ci = (map <= map_ci_H99) & (map >= map_ci_L99),
      within_pi = (map <= map_pi_H99) & (map >= map_pi_L99)
    ) %>>%
    group_by(elint, phase) %>>%
    mutate(n_within_pi = sum(within_pi)) %>>%
    ungroup() %>>%
    mutate(map = ifelse(within_pi == 0, map_est, map)) %>>%
    # filter(within_ci) %>>%
    filter(within_pi | n_within_pi == 0) %>>%
    group_by(elint, phase) %>>%
    summarise(map = median(map)) %>>%
    ungroup %>>%
    spread(elint, map) %>>%
    (~ if(is.character(saving)) fwrite(., saving)) %>>%
    # (~ print(.)) %>>%
    return()

}
















