menu_map <- function(id, dropdown = NULL) {
  ids <- paste0(id, "_", c("elem_selecter", "min", "max"))
  cssgrid::grid_layout(
    shiny::uiOutput(ids[[1L]]), # selectInput of elements generated by select_elem
    shiny::numericInput(ids[[2L]], "Min", value = NA_real_, width = "100%"),
    shiny::numericInput(ids[[3L]], "Max", value = NA_real_, width = "100%"),
    dropdown,
    cols = "8em 1fr 1fr auto",
    column_gap = "3px",
    style = "width: 100%;",
    class = "cssgrid"
  )
}

picker_input <- function(
  inputId, label = NULL, choices,
  options = list(style = "form-control shiny-bound-input"),
  ...
) {
  shinyWidgets::pickerInput(
    inputId = inputId, label = label, choices = choices, 
    options = options, ...
  )
}

drop_map <- function(id, ...) {
  #div(
  shinyWidgets::dropdown(
    picker_input(
      paste0(id, "_color"), label = "Color", 
      choices = c("viridis", "gray"),
      selected = "viridis", width = "100%"
    ),
    ...,
    circle = FALSE, right = TRUE, width = "200px"
  )#, style = "align-self: end; margin-bottom: 15px;")
}

select_action <- function(id) {
  shinyWidgets::radioGroupButtons(
    inputId = id,
    label = "Mouse actions",
    choices = c("Zoom", "Move", "Summarize"),
    selected = "Zoom",
    status = "secondary",
    individual = TRUE
  )
}

message_action <- c(
  Zoom = "Zoom by double click selected area. Pan by double click again.",
  Move = "Move by double click within zoomed area.",
  Summarize = "Double click or select area to save data."
)

